backend:
  name: git-gateway
  branch: develop
media_folder: "public/assets/posts"
public_folder: "/assets/posts"

i18n:
  structure: multiple_folders
  locales: [en, fr]
  default_locale: en

collections:
  - name: "post"
    label: "Post"
    folder: "src"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.masterTitle}}"
    fields:
      - {
          label: "Layout",
          name: "layout",
          widget: "hidden",
          i18n: duplicate,
          default: "layouts/article"
        }
      - {
          label: "Master Title",
          name: "masterTitle",
          widget: "string",
          i18n: duplicate,
          hint: "This is the master post title for all locales"
        }
      - {
          label: "Publish",
          name: "isPublished",
          widget: "boolean",
          default: true,
          i18n: duplicate,
          hint: "Toggle to publish or unpublish post"
        }
      - {
          label: "Featured Post",
          name: "isFeatured",
          widget: "boolean",
          default: false,
          i18n: duplicate,
          hint: "Toggle to promote post to Home featured section"
        }
      - {
          label: "Machine Translated",
          name: "isMachineTranslated",
          widget: "boolean",
          default: false,
          i18n: true,
          hint: "If post is machine translated"
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true
        }
      - { label: "Date", name: "date", widget: "datetime", i18n: duplicate }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
          i18n: duplicate
        }
      - {
          label: "Image Caption",
          name: "imageAlt",
          widget: "string",
          required: false,
          i18n: duplicate
        }
      - { label: "Body", name: "body", widget: "markdown", i18n: true }
  - name: "project"
    label: "Project"
    folder: "src/_data/projects"
    create: true
    i18n: true
    slug: "{{year}}-{{month}}-{{day}}-{{fields.masterTitle}}"
    fields:
      - {
          label: "Master Title",
          name: "masterTitle",
          widget: "string",
          i18n: duplicate,
          hint: "This is the master post title for all locales"
        }
      - {
          label: "Publish",
          name: "isPublished",
          widget: "boolean",
          default: true,
          i18n: duplicate,
          hint: "Toggle to publish or unpublish post"
        }
      - {
          label: "Machine Translated",
          name: "isMachineTranslated",
          widget: "boolean",
          default: false,
          i18n: true,
          hint: "If post is machine translated"
        }
      - { label: "Title", name: "title", widget: "string", i18n: true }
      - {
          label: "Description",
          name: "description",
          widget: "string",
          i18n: true
        }
      - { label: "Date", name: "date", widget: "datetime", i18n: duplicate }
      - {
          label: "Featured Image",
          name: "image",
          widget: "image",
          required: false,
          i18n: duplicate
        }
      - {
          label: "Image Caption",
          name: "imageAlt",
          widget: "string",
          required: false,
          i18n: duplicate
        }
      - {
          label: "Github Link",
          name: "gitLink",
          widget: "string",
          required: false,
          i18n: duplicate
        }
      - {
          label: "Project Link",
          name: "siteLink",
          widget: "string",
          required: false,
          i18n: duplicate
        }
